name: CI

on:
  pull_request:
  push:
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        name: Cache ~/.stack
        with:
          path: ~/.stack
          key: stack-global-${{ hashFiles('stack.yaml') }}
          restore-keys: stack-global-

      - uses: haskell/actions/setup@v2
        name: Setup Haskell Stack
        with:
          stack-version: latest
          stack-no-global: true
          stack-setup-ghc: true
          enable-stack: true

      - name: Install non-hs dependencies
        run: sudo apt-get update && sudo apt-get install libgtk-3-dev gobject-introspection libgirepository1.0-dev libwebkit2gtk-4.0-dev libgtksourceview-3.0-dev

      - name: Install dependencies
        run: |
          stack build --test --bench --no-run-tests --no-run-benchmarks --only-dependencies
      - name: Build
        run: |
          stack build --test --bench --no-run-tests --no-run-benchmarks
      - name: Test
        run: |
          stack test
